# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 1, the first  terms will be:
# 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const fibo_max = Int64(4e6)

fibo = [1, 1]
while sum(fibo) <= fibo_max
    fibo = insert!(fibo, 1, fibo[1] + fibo[2])
end

if sum(fibo) > fibo_max fibo[1] = 0 end

sum(filter(iseven, fibo))